### PR TITLE
Develop stream 20210308

### PR DESCRIPTION
**Pull request by neon60**
* Add thread algorithms

### CODE REVIEW

**Review by stanleytsang-amd — APPROVED** [review]

**Comment by doctorcolinsmith** [comment]
It looks like the failed jobs are all related to documentation build fails.  We can investigate that seperately.

**Review by doctorcolinsmith — APPROVED** [review]

**Review by saadrahim — CHANGES_REQUESTED** [review]
The documentation CI failure is actually a real issue. You should build the documentation and fix the problem. Adding lines to disable doc generation is likely the best approach.

**Comment by neon60** [comment]
> The documentation CI failure is actually a real issue. You should build the documentation and fix the problem. Adding lines to disable doc generation is likely the best approach.

I updated the documentation in the next PR: 
https://github.com/ROCmSoftwarePlatform/hipCUB/pull/127

I think we can close this PR, merge in 127.

**Comment by saadrahim** [comment]
Is this PR superseded by PR#127? Should this be close?

**Comment by neon60** [comment]
> Is this PR superseded by PR#127? Should this be close?

Previous comment :) : 
> I think we can close this PR, merge in 127.

Please check the PR 127.

**Comment by neon60** [comment]
I can actually close this. So please check:
https://github.com/ROCmSoftwarePlatform/hipCUB/pull/127

**Pull request closed without merging**
