### PR TITLE
Missing includes

### PR DESCRIPTION
**Pull request by neon60**
Missing includes

### CODE REVIEW

**Comment by saadrahim** [comment]
The documentation for hipcub is not building. Can you check why?

**Comment by saadrahim** [comment]
builds are still failing. ! Emergency stop.
 ...                                              
                                                  
l.961 ...xincludegraphics{{docBin/xml/raking}.png}
                                                  
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on hipCUB.log.
Latexmk: Index file 'hipCUB.idx' was written
Latexmk: Missing input file: '{docBin/xml/raking}.png' from line
  'LaTeX Warning: File `{docBin/xml/raking}.png' not found on input line 961.'
Latexmk: Missing input file: '{docBin/xml/raking}.png' from line
  'LaTeX Warning: File `{docBin/xml/raking}.png' not found on input line 961.'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 256
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs of latex/pdflatex.
Latexmk: Errors, so I did not complete making targets
Makefile:29: recipe for target 'hipCUB.pdf' failed
make[1]: *** [hipCUB.pdf] Error 12
make[1]: Leaving directory '/var/jenkins_home/workspace/ng_Static_Analysis_hipCUB_PR-147/nzokHZDDi/hipcub/docs/_build/latex'

Makefile:20: recipe for target 'latexpdf' failed
make: *** [latexpdf] Error 2
Looks like some images might be missing.

**Comment by neon60** [comment]
> builds are still failing. ! Emergency stop.
> ...
> 
> l.961 ...xincludegraphics{{docBin/xml/raking}.png}
> 
> ! ==> Fatal error occurred, no output PDF file produced!
> Transcript written on hipCUB.log.
> Latexmk: Index file 'hipCUB.idx' was written
> Latexmk: Missing input file: '{docBin/xml/raking}.png' from line
> 'LaTeX Warning: File `{docBin/xml/raking}.png' not found on input line 961.' Latexmk: Missing input file: '{docBin/xml/raking}.png' from line 'LaTeX Warning: File `{docBin/xml/raking}.png' not found on input line 961.'
> Collected error summary (may duplicate other messages):
> pdflatex: Command for 'pdflatex' gave return code 256
> Latexmk: Use the -f option to force complete processing,
> unless error was exceeding maximum runs of latex/pdflatex.
> Latexmk: Errors, so I did not complete making targets
> Makefile:29: recipe for target 'hipCUB.pdf' failed
> make[1]: *** [hipCUB.pdf] Error 12
> make[1]: Leaving directory '/var/jenkins_home/workspace/ng_Static_Analysis_hipCUB_PR-147/nzokHZDDi/hipcub/docs/_build/latex'
> 
> Makefile:20: recipe for target 'latexpdf' failed
> make: *** [latexpdf] Error 2
> Looks like some images might be missing.

Thanks. I can check this later.

**Comment by neon60** [comment]
It's part of a separate PR.

**Pull request closed without merging**
