### PR TITLE
Fix documentation + add bfloat16 support to device radix sort

### PR DESCRIPTION
**Pull request by neon60**
Fix documentation + add bfloat16 support to device radix sort( https://github.com/ROCmSoftwarePlatform/hipCUB/pull/149 )

### CODE REVIEW

**Comment by neon60** [comment]
@stanleytsang-amd @saadrahim @doctorcolinsmith  Can I get the error messages?

**Comment by doctorcolinsmith** [comment]
PR is failing on the documentation checks.  @stanleytsang-amd Can you please take a look and send the errors to @neon60 ?

**Comment by neon60** [comment]
> PR is failing on the documentation checks. @stanleytsang-amd Can you please take a look and send the errors to @neon60 ?

We are adding to the gitlab CI this step. Currently I can't reproduce the problem at our side. I will request documentation package version numbers from you.

**Comment by neon60** [comment]
Fixed and added a CI step to gitlab CI.

**Review by stanleytsang-amd — APPROVED** [review]

**Pull request merged**
