### PR TITLE
Add hip-clang install to install script

### PR DESCRIPTION
**Pull request by aaronenyeshi**
Adding HIP-Clang path to use hipcc to compile hipCUB

### CODE REVIEW

**Comment by saadrahim** [comment]
Please change the branch to develop. All commits must go to develop first.

**Comment by aaronenyeshi** [comment]
@saadrahim  it seems the develop branch is older than the master branch. It is missing the -p (package) option in the install script. Should I still change to develop?

**Comment by saadrahim** [comment]
Please wait, there are issue here that need manual fixes

**Comment by saadrahim** [comment]
Please change to develop now.

**Pull request merged**
